apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    base: minio
  name: minio
spec:
  selector:
    matchLabels:
      base: minio
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: minio
        args:
        - server
        - --address
        - 0.0.0.0:9000
        - /data
        env:
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: MINIO_SECRET_KEY
              name: minio-secret
        - name: MINIO_ACCESS_KEY
          value: minio
        image: minio/minio:RELEASE.2020-11-19T23-48-16Z
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: minio
        resources:
          limits:
            memory: 5Gi
            cpu: 1000m
          requests:
            memory: 3Gi
            cpu: 500m
        volumeMounts:
        - mountPath: /data
          name: minio-data
          subPath: minio
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data-pvc