apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  base: minio

resources:
  - deployment.yaml
  - service.yaml
  - pvc-data.yaml
  
secretGenerator:
  - name: minio-secret
    literals:
      - MINIO_SECRET_KEY=securepassword
