apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  base: mongodb

resources:
  - deployment.yaml
  - service.yaml
  - pvc-data.yaml
  
secretGenerator:
  - name: mongodb-secret
    literals:
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
